name: Deploy
on:
  push:
    branches:
      - main # 只有在main分支push代码时才会触发
jobs:
  deploy:
    runs-on: ubuntu-latest # 运行环境
    steps:
      - name: Checkout # 检出代码
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0' # 指定所需的 Node.js 版本
      - name: Build # 打包
        run: npm run build
      - name: Deploy # 部署
        uses: easingthemes/ssh-deploy@v2
        with:
          server: ${{ secrets.SERVER }} # 服务器地址
          username: ${{ secrets.USERNAME }} # 用户名
          password: ${{ secrets.PASSWORD }} # 密码
          local_path: ./public # 本地打包路径
          server_path: /www/wwwroot/myVuepressblog/ # 服务器部署路径
