name: Deploy to Baota

on:
  push:
    branches:
      - main  # 或者您的默认分支

jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0' # 指定所需的 Node.js 版本
          
      - name: Build
        run: npm run build

      - name: Deploy to Baota
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.BAOTA_API_KEY }}" \
            -d '{"domain": "www.wcrlayue.top:10086", "path": "/www/wwwroot/www.wcr.top/", "source_path": "dist"}' \
            https://www.wcrlayue.top:8089/lu7368
