
name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

         #添加权限
      - name: Restore permissions of node_modules
        run: chmod -R +x node_modules


      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build
        run: npm run build
       #easingthemes/ssh-deploy@v2
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          #password: ${{ secrets.REMOTE_PASSWORD }}
          #port: ${{ secrets.REMOTE_PORT }}
          entryPoint: rsync -az --delete ./public/ $${{ secrets.REMOTE_USER }}@$${{ secrets.REMOTE_HOST }}:/www/wwwroot/myVuepressblog/
          args: -rltgoDzvO
